### ISSUE TITLE
Errors in veml6040.cpp

### ISSUE THREAD

**Issue by shaunakm** [thewknd/VEML6040#1]
Hi,

Thanks for creating the library. It helped me for my project, though there are some minor bugs in the _veml6040.cpp_ file. They are
1.  Instead of _VEML6040.h_, it should be _veml6040.h_.
2. Include _math.h_ in the same file to calculate power.

Anyways thanks for the library.
Regards,
Shaunak

**Comment by tobozo** [comment]
just made a [pull request](https://github.com/thewknd/VEML6040/pull/3/commits/8d8f332d7a3764a4076724069d49e6265190801f) for that, not sure I did it right though.

thanks for the good work!
